-- Cambio exclusivamente aditivo. Revisar/aplicar si Hibernate no administra el esquema.
-- No contiene tokens, credenciales ni cambios a usuarios existentes.
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    token_version BIGINT NOT NULL
);
